### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by Reshy** [TeamDeusVult/MagnesiumExtras#25]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rubidium_extras.mixins.json:JEI.IngredientListOverlayMixin] from phase [DEFAULT] in config [rubidium_extras.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 45 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field searchField was not located in the target class mezz.jei.gui.overlay.IngredientListOverlay. Using refmap rubidium_extras.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 45 more

Crash Log:  https://pastebin.com/EjZUQSwG

**Comment by semisp** [comment]
Getting the same crash here.

**Comment by Tander** [comment]
+1

[crash-2022-07-27_17.44.13-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/9200382/crash-2022-07-27_17.44.13-client.txt) (reproduced on a clean setup)

**Comment by Nevrai** [comment]
I’m having the same issue. My game is crashing when I enter a world. Using the latest alpha version of JEI for 1.18.2 fixes the issue. Disabling “Hide JEI Until Searching” in Rubidium Extras’ config does too. In my opinion, that should be set to false in this mod by default.

**Relevant part of latest.log:** https://pastebin.com/raw/9tqtPeXQ

**Versions:**
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69 (latest)
* **Rubidium Extras:** 1.3.1 (latest)
* **Just Enough Items:** 9.7.1.232 (latest release version for 1.18.2)

**Comment by Chaos02** [comment]
still having this crash!
It is resolved in JEI version 10 and above but that version is a NOGO when using mods implementing FLUID handling crafting recipes!!
Source: https://github.com/mezz/JustEnoughItems/issues/2936#issuecomment-1207075193

### This is a great mod but the JEI search tweak should not be a part of it!!

Here is the ERROR log: [https://pastebin.com/atV445y8](https://pastebin.com/atV445y8)

@Tander @Reshy @DeleteMetaInf @semisp @ItsSyfe
